name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.repository == 'nomifactory-ja/nomifactory-ja'

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID_DANGERBOT }}
          private_key: ${{ secrets.APP_PEM_DANGERBOT }}

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: "Download NPM packages"
        run: npm ci

      - name: "Danger"
        run: npx danger ci --removePreviousComments
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
