name: Nightly Builds

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  nightly:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags --force

      - name: Restore cached files
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.npm
            ./.cache
            ./node_modules
          key: ${{ runner.os }}-bunny-${{ hashFiles('**/.cache', '**/package-lock.json', '**/manifest.json') }}
          restore-keys: ${{ runner.os }}-bunny-

      - name: "Setup NodeJS v16"
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          check-latest: true

      - name: "Download NPM packages"
        run: npm ci

      - name: "Build ResourcePack"
        run: npm run build

      ##
      ## Upload artifacts.
      ##
      - name: "Make artifact names"
        id: artifactNames
        run: npx gulp makeArtifactNames

      - name: "Upload lang artifact"
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.artifactNames.outputs.lang }}
          path: |
            build/**/*
